FROM  --platform=linux/arm64 alpine:latest

EXPOSE 3000

COPY ./server /server

RUN  apk add shadow
RUN  useradd api && \
  mkdir -p /var/lib/amazon && \
  chmod 750 /var/lib/amazon && \
  mkdir -p /var/log/amazon && \
  chmod 700 /var/log/amazon && \
  chmod +x /server

VOLUME /var/lib/amazon /var/log/amazon

CMD ["./server"]
