# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ja-JP"
early_access: true
enable_free_tier: false
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@auto-summary"
  auto_title_placeholder: "@auto-title"
  auto_title_instructions: |
    あなたはPull Requestのタイトルを整形する専門家です。
    以下のルールに従って、PRの内容を分析し、最適な絵文字とプレフィックスを付けてタイトルを生成してください:

    # バグ修正
    🐛 重大なバグ修正
    🩹 軽微なバグ修正

    # 機能追加/改善
    🎉 大規模な機能追加
    ✨ 新機能追加
    👍 既存機能の改善
    🔧 細かな機能調整

    # 最適化
    🚀 パフォーマンス改善の場合

    # リファクタ
    ♻️ リファクタリング
    🧹 コードの整理・クリーンアップ
    🎨 コードスタイルの改善

    # テスト
    🧪 テストの追加
    💚 CI/CDの改善
    ✅ テストの修正

    # 依存関係
    🆙 依存関係更新
    📦 パッケージの追加
    🗑️ パッケージの削除

    # 設定
    📝 設定ファイルの変更

    # ドキュメント
    📚 ドキュメント更新
    💬 コメント改善
    📖 README更新

    ルール:
    1. 必ず絵文字をを含めること
    2. 変更内容を簡潔に表現すること
    3. 複数の種類の変更がある場合は、最も重要な変更に基づいて選択すること
    4. タイトルは必ず日本語で記述すること
    5. 末尾に句点や感嘆符を付けないこと

  poem: true
  collapse_walkthrough: true
  sequence_diagrams: true
  changed_files_summary: true
  suggested_labels: true
  abort_on_close: true
  auto_apply_labels: true
  labeling_instructions:
    - label: "dependencies"
      instructions: "依存関係の更新やライブラリのバージョンアップを含むPRに適用します。セキュリティアップデートも含みます"
    - label: "performance"
      instructions: "パフォーマンス改善や最適化を含むPRに適用します。実行速度の向上やリソース使用効率の改善が該当します"
    - label: "testing"
      instructions: "テストコードの追加や改善、テスト環境の設定変更を含むPRに適用します"
    - label: "refactor"
      instructions: "コードのリファクタリングや整理を含むPRに適用します。機能の変更を伴わない内部実装の改善が該当します"
  path_filters:
    - "cmd/**"
    - "container/**"
    - "internal/**"
    - "migrations/**"
    - ".sqlc.yaml"
    - "README.md"
    - "oapi.yaml"
    - "ogen.yml"
    - ".github/**"
  tools:
    shellcheck:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    golangci-lint:
      enabled: true
    actionlint:
      enabled: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    ignore_title_keywords:
      - "WIP"
chat:
  auto_reply: true
knowledge_base:
  opt_out: false
  learnings:
    scope: "auto"
  issues:
    scope: "auto"
  pull_requests:
    scope: "auto"
