# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ja-JP"
early_access: true
enable_free_tier: true
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  auto_title_placeholder: "@auto"
  poem: true
  review_status: true
  collapse_walkthrough: false
  sequence_diagrams: true
  suggested_labels: true
  abort_on_close: true
  path_filters:
    - "cmd/**"
    - "container/**"
    - "internal/**"
    - "migrations/**"
    - ".sqlc.yaml"
    - "README.md"
    - "oapi.yaml"
    - "ogen.yml"
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
