# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ja-JP"
early_access: true
enable_free_tier: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@auto-summary"
  auto_title_placeholder: "@auto-title"
  review_status: false
  poem: true
  collapse_walkthrough: true
  sequence_diagrams: true
  changed_files_summary: true
  suggested_labels: true
  abort_on_close: true
  labeling_instructions:
    - label: "dependencies"
      instructions: "依存関係の更新やライブラリのバージョンアップを含むPRに適用します。セキュリティアップデートも含みます"
    - label: "performance"
      instructions: "パフォーマンス改善や最適化を含むPRに適用します。実行速度の向上やリソース使用効率の改善が該当します"
    - label: "testing"
      instructions: "テストコードの追加や改善、テスト環境の設定変更を含むPRに適用します"
    - label: "refactor"
      instructions: "コードのリファクタリングや整理を含むPRに適用します。機能の変更を伴わない内部実装の改善が該当します"

  path_filters:
    - "cmd/**"
    - "container/**"
    - "internal/**"
    - "migrations/**"
    - ".sqlc.yaml"
    - "README.md"
    - "oapi.yaml"
    - "ogen.yml"
    - ".github/**"
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
