[tools]
"go:github.com/ogen-go/ogen/cmd/ogen" = "latest"
jq = "latest"
"go:github.com/air-verse/air" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
"npm:swagger-merger" = "latest"
go = "1.23.0"
"go:go.uber.org/mock/mockgen" = "latest"
"npm:@openapitools/openapi-generator-cli" = "latest"
"go:github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen" = "v2.2.0"
"go:github.com/hedhyw/otelinji/cmd/otelinji" = "latest"
"go:github.com/k1LoW/runn/cmd/runn" = "latest"
task = "latest"
"go:github.com/dmarkham/enumer" = "latest"

[tasks.migrate-create]
description = "Create a new migration file"
run = "./scripts/migrate-create.sh "

[tasks.migrate-up]
description = "Run all migrations"
env = { DB_URL = "postgres://kotohiro:kotohiro@localhost:5432/kotohiro?sslmode=disable" }
run = "migrate -path migrations -database \"$DB_URL\" up"

[tasks.migrate-down]
description = "Rollback last migration"
env = { DB_URL = "postgres://kotohiro:kotohiro@localhost:5432/kotohiro?sslmode=disable" }
run = "migrate -path migrations -database \"$DB_URL\" down 1"

[tasks.migrate-status]
description = "Show migration status"
env = { DB_URL = "postgres://kotohiro:kotohiro@localhost:5432/kotohiro?sslmode=disable" }
run = "migrate -path migrations -database \"$DB_URL\" version"
