[tools]
"go:github.com/ogen-go/ogen/cmd/ogen" = "latest"
jq = "latest"
"go:github.com/air-verse/air" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
"npm:swagger-merger" = "latest"
go = "latest"
"go:go.uber.org/mock/mockgen" = "latest"
"npm:@openapitools/openapi-generator-cli" = "latest"
"go:github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen" = "v2.2.0"
