[tools]
"go:github.com/ogen-go/ogen/cmd/ogen" = "latest"
yq = "latest"
jq = "latest"
"go:github.com/masaushi/accessory" = "latest"
"go:github.com/pressly/goose/v3/cmd/goose" = "latest"
"go:github.com/swaggest/swgui/cmd/swgui" = "latest"
