[tools]
"go:github.com/air-verse/air" = "v1.61.7"
"npm:@openapitools/openapi-generator-cli" = "latest"
"npm:@typespec/compiler" = "latest"
ecspresso = "latest"
go = "1.25.1"
jq = "latest"
task = "latest"

[tasks.migrate-create]
description = "Create a new migration file"
run = "./scripts/migrate-create.sh "

[tasks.migrate-up]
description = "Run all migrations"
env = { DB_URL = "postgres://kotohiro:kotohiro@localhost:5432/kotohiro?sslmode=disable" }
run = "migrate -path migrations -database \"$DB_URL\" up"

[tasks.migrate-down]
description = "Rollback last migration"
env = { DB_URL = "postgres://kotohiro:kotohiro@localhost:5432/kotohiro?sslmode=disable" }
run = "migrate -path migrations -database \"$DB_URL\" down 1"

[tasks.migrate-status]
description = "Show migration status"
env = { DB_URL = "postgres://kotohiro:kotohiro@localhost:5432/kotohiro?sslmode=disable" }
run = "migrate -path migrations -database \"$DB_URL\" version"
