repository: neko-dream/api
coverage:
  paths:
    - coverage.out
codeToTestRatio:
  codeToTestRatio:
  code:
    - "**/*.go"
    - "!**/*_test.go"
    - "!internal/presentation/oas/**"
    - "!internal/infrastructure/persistence/sqlc/generated/**"
  test:
    - "**/*_test.go"
testExecutionTime:
  if: true
report:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
summary:
  if: true
