services:
  db:
    image: ghcr.io/baosystems/postgis:15-3.5
    container_name: pg
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./container/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: kotohiro
      POSTGRES_USER: kotohiro
      POSTGRES_PASSWORD: kotohiro
volumes:
  pgdata:
