
DROP TABLE IF EXISTS "user_auths" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "talk_session_locations" CASCADE;
DROP TABLE IF EXISTS "talk_sessions" CASCADE;
DROP TABLE IF EXISTS "opinions" CASCADE;
DROP TABLE IF EXISTS "votes" CASCADE;
DROP TABLE IF EXISTS "sessions" CASCADE;
DROP TABLE IF EXISTS "user_demographics" CASCADE;

DROP EXTENSION IF EXISTS postgis CASCADE;
DROP TABLE IF EXISTS spatial_ref_sys CASCADE;
