/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TalksessionsImport } from './routes/talksessions'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TalksessionsRoute = TalksessionsImport.update({
  id: '/talksessions',
  path: '/talksessions',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/talksessions': {
      id: '/talksessions'
      path: '/talksessions'
      fullPath: '/talksessions'
      preLoaderRoute: typeof TalksessionsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/talksessions': typeof TalksessionsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/talksessions': typeof TalksessionsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/talksessions': typeof TalksessionsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/talksessions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/talksessions'
  id: '__root__' | '/' | '/talksessions'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TalksessionsRoute: typeof TalksessionsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TalksessionsRoute: TalksessionsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/talksessions"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/talksessions": {
      "filePath": "talksessions.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
