// Code generated by ogen, DO NOT EDIT.
package oas

type ApplyFeedbackToReportRes interface {
	applyFeedbackToReportRes()
}

type AuthAccountDetachRes interface {
	authAccountDetachRes()
}

type AuthorizeRes interface {
	authorizeRes()
}

type ChangePasswordRes interface {
	changePasswordRes()
}

type CheckDeviceExistsRes interface {
	checkDeviceExistsRes()
}

type ConsentTalkSessionRes interface {
	consentTalkSessionRes()
}

type CreateOrganizationAliasRes interface {
	createOrganizationAliasRes()
}

type DeleteDeviceRes interface {
	deleteDeviceRes()
}

type DeleteOrganizationAliasRes interface {
	deleteOrganizationAliasRes()
}

type DevAuthorizeRes interface {
	devAuthorizeRes()
}

type DummiInitRes interface {
	dummiInitRes()
}

type EditTalkSessionRes interface {
	editTalkSessionRes()
}

type EditTimeLineRes interface {
	editTimeLineRes()
}

type EstablishOrganizationRes interface {
	establishOrganizationRes()
}

type EstablishUserRes interface {
	establishUserRes()
}

type GetConclusionRes interface {
	getConclusionRes()
}

type GetDevicesRes interface {
	getDevicesRes()
}

type GetNotificationPreferencesRes interface {
	getNotificationPreferencesRes()
}

type GetOpenedTalkSessionRes interface {
	getOpenedTalkSessionRes()
}

type GetOpinionAnalysisRes interface {
	getOpinionAnalysisRes()
}

type GetOpinionDetail2Res interface {
	getOpinionDetail2Res()
}

type GetOpinionReportReasonsRes interface {
	getOpinionReportReasonsRes()
}

type GetOpinionReportsRes interface {
	getOpinionReportsRes()
}

type GetOpinionsForTalkSessionRes interface {
	getOpinionsForTalkSessionRes()
}

type GetOrganizationAliasesRes interface {
	getOrganizationAliasesRes()
}

type GetOrganizationUsersRes interface {
	getOrganizationUsersRes()
}

type GetOrganizationsRes interface {
	getOrganizationsRes()
}

type GetPolicyConsentStatusRes interface {
	getPolicyConsentStatusRes()
}

type GetReportsForTalkSessionRes interface {
	getReportsForTalkSessionRes()
}

type GetTalkSessionDetailRes interface {
	getTalkSessionDetailRes()
}

type GetTalkSessionListRes interface {
	getTalkSessionListRes()
}

type GetTalkSessionReportCountRes interface {
	getTalkSessionReportCountRes()
}

type GetTalkSessionReportRes interface {
	getTalkSessionReportRes()
}

type GetTalkSessionRestrictionKeysRes interface {
	getTalkSessionRestrictionKeysRes()
}

type GetTalkSessionRestrictionSatisfiedRes interface {
	getTalkSessionRestrictionSatisfiedRes()
}

type GetTimeLineRes interface {
	getTimeLineRes()
}

type GetTokenInfoRes interface {
	getTokenInfoRes()
}

type GetUserByDisplayIDRes interface {
	getUserByDisplayIDRes()
}

type GetUserInfoRes interface {
	getUserInfoRes()
}

type HandleAuthCallbackRes interface {
	handleAuthCallbackRes()
}

type HasConsentRes interface {
	hasConsentRes()
}

type HealthRes interface {
	healthRes()
}

type InitiateTalkSessionRes interface {
	initiateTalkSessionRes()
}

type InviteOrganizationForUserRes interface {
	inviteOrganizationForUserRes()
}

type InviteOrganizationRes interface {
	inviteOrganizationRes()
}

type OpinionComments2Res interface {
	opinionComments2Res()
}

type OpinionsHistoryRes interface {
	opinionsHistoryRes()
}

type PasswordLoginRes interface {
	passwordLoginRes()
}

type PasswordRegisterRes interface {
	passwordRegisterRes()
}

type PolicyConsentRes interface {
	policyConsentRes()
}

type PostConclusionRes interface {
	postConclusionRes()
}

type PostImageRes interface {
	postImageRes()
}

type PostOpinionPost2Res interface {
	postOpinionPost2Res()
}

type PostTimeLineItemRes interface {
	postTimeLineItemRes()
}

type ReactivateUserRes interface {
	reactivateUserRes()
}

type RegisterDeviceRes interface {
	registerDeviceRes()
}

type ReportOpinionRes interface {
	reportOpinionRes()
}

type RevokeTokenRes interface {
	revokeTokenRes()
}

type SendTestNotificationRes interface {
	sendTestNotificationRes()
}

type SessionsHistoryRes interface {
	sessionsHistoryRes()
}

type SolveOpinionReportRes interface {
	solveOpinionReportRes()
}

type SwipeOpinionsRes interface {
	swipeOpinionsRes()
}

type TalkSessionAnalysisRes interface {
	talkSessionAnalysisRes()
}

type TestRes interface {
	testRes()
}

type UpdateNotificationPreferencesRes interface {
	updateNotificationPreferencesRes()
}

type UpdateUserProfileRes interface {
	updateUserProfileRes()
}

type ValidateOrganizationCodeRes interface {
	validateOrganizationCodeRes()
}

type Vote2Res interface {
	vote2Res()
}

type WithdrawUserRes interface {
	withdrawUserRes()
}
