// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AuthLogin implements auth_login operation.
//
// OAuthログイン.
//
// GET /auth/{provider}/login
func (UnimplementedHandler) AuthLogin(ctx context.Context, params AuthLoginParams) (r *AuthLoginFound, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTalkSession implements createTalkSession operation.
//
// トークセッション作成.
//
// POST /api/talksessions
func (UnimplementedHandler) CreateTalkSession(ctx context.Context, req OptCreateTalkSessionReq) (r *CreateTalkSessionOK, _ error) {
	return r, ht.ErrNotImplemented
}

// EditUserProfile implements editUserProfile operation.
//
// ユーザー情報の変更.
//
// PUT /api/user
func (UnimplementedHandler) EditUserProfile(ctx context.Context, req OptEditUserProfileReq) (r EditUserProfileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTalkSessionDetail implements getTalkSessionDetail operation.
//
// トークセッションの詳細.
//
// GET /api/talksessions/{talkSessionId}
func (UnimplementedHandler) GetTalkSessionDetail(ctx context.Context, params GetTalkSessionDetailParams) (r *GetTalkSessionDetailOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTalkSessions implements getTalkSessions operation.
//
// トークセッションコレクション.
//
// GET /api/talksessions
func (UnimplementedHandler) GetTalkSessions(ctx context.Context) (r *GetTalkSessionsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTopOpinions implements getTopOpinions operation.
//
// 🚧 分析に関する意見.
//
// GET /api/talksessions/{talkSessionId}/opinion
func (UnimplementedHandler) GetTopOpinions(ctx context.Context, params GetTopOpinionsParams) (r GetTopOpinionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserProfile implements getUserProfile operation.
//
// ユーザー情報の取得.
//
// GET /api/user
func (UnimplementedHandler) GetUserProfile(ctx context.Context) (r *GetUserProfileOK, _ error) {
	return r, ht.ErrNotImplemented
}

// Intention implements Intention operation.
//
// 意思表明API.
//
// POST /api/talksessions/{talkSessionID}/opinions/{opinionID}/intentions
func (UnimplementedHandler) Intention(ctx context.Context, req OptIntentionReq, params IntentionParams) (r IntentionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOpinions implements listOpinions operation.
//
// ランダムな意見.
//
// GET /api/talksession/{talkSessionID}/opinions
func (UnimplementedHandler) ListOpinions(ctx context.Context, params ListOpinionsParams) (r ListOpinionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OAuthCallback implements oauth_callback operation.
//
// Auth Callback.
//
// GET /auth/{provider}/callback
func (UnimplementedHandler) OAuthCallback(ctx context.Context, params OAuthCallbackParams) (r *OAuthCallbackFound, _ error) {
	return r, ht.ErrNotImplemented
}

// OpinionComments implements opinionComments operation.
//
// 意見に対するコメント一覧を返す.
//
// GET /api/talksession/{talkSessionID}/opinions/{opinionID}
func (UnimplementedHandler) OpinionComments(ctx context.Context, params OpinionCommentsParams) (r OpinionCommentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostOpinionPost implements postOpinionPost operation.
//
// セッションに対して意見投稿.
//
// POST /api/talksessions/{talkSessionID}/opinions
func (UnimplementedHandler) PostOpinionPost(ctx context.Context, req OptPostOpinionPostReq, params PostOpinionPostParams) (r PostOpinionPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterUser implements registerUser operation.
//
// ユーザー作成.
//
// POST /api/user
func (UnimplementedHandler) RegisterUser(ctx context.Context, req OptRegisterUserReq) (r RegisterUserRes, _ error) {
	return r, ht.ErrNotImplemented
}
