// Code generated by ogen, DO NOT EDIT.
package oas

type AuthAccountDetachRes interface {
	authAccountDetachRes()
}

type AuthorizeRes interface {
	authorizeRes()
}

type CreateTalkSessionRes interface {
	createTalkSessionRes()
}

type DevAuthorizeRes interface {
	devAuthorizeRes()
}

type DummiInitRes interface {
	dummiInitRes()
}

type EditTalkSessionRes interface {
	editTalkSessionRes()
}

type EditTimeLineRes interface {
	editTimeLineRes()
}

type EditUserProfileRes interface {
	editUserProfileRes()
}

type GetConclusionRes interface {
	getConclusionRes()
}

type GetOpenedTalkSessionRes interface {
	getOpenedTalkSessionRes()
}

type GetOpinionAnalysisRes interface {
	getOpinionAnalysisRes()
}

type GetOpinionDetail2Res interface {
	getOpinionDetail2Res()
}

type GetOpinionDetailRes interface {
	getOpinionDetailRes()
}

type GetOpinionReportReasonsRes interface {
	getOpinionReportReasonsRes()
}

type GetOpinionReportsRes interface {
	getOpinionReportsRes()
}

type GetOpinionsForTalkSessionRes interface {
	getOpinionsForTalkSessionRes()
}

type GetPolicyConsentStatusRes interface {
	getPolicyConsentStatusRes()
}

type GetReportsForTalkSessionRes interface {
	getReportsForTalkSessionRes()
}

type GetTalkSessionDetailRes interface {
	getTalkSessionDetailRes()
}

type GetTalkSessionListRes interface {
	getTalkSessionListRes()
}

type GetTalkSessionReportCountRes interface {
	getTalkSessionReportCountRes()
}

type GetTalkSessionReportRes interface {
	getTalkSessionReportRes()
}

type GetTalkSessionRestrictionKeysRes interface {
	getTalkSessionRestrictionKeysRes()
}

type GetTalkSessionRestrictionSatisfiedRes interface {
	getTalkSessionRestrictionSatisfiedRes()
}

type GetTimeLineRes interface {
	getTimeLineRes()
}

type GetUserInfoRes interface {
	getUserInfoRes()
}

type OAuthCallbackRes interface {
	oAuthCallbackRes()
}

type OAuthTokenInfoRes interface {
	oAuthTokenInfoRes()
}

type OAuthTokenRevokeRes interface {
	oAuthTokenRevokeRes()
}

type OpinionComments2Res interface {
	opinionComments2Res()
}

type OpinionCommentsRes interface {
	opinionCommentsRes()
}

type OpinionsHistoryRes interface {
	opinionsHistoryRes()
}

type PasswordLoginRes interface {
	passwordLoginRes()
}

type PasswordRegisterRes interface {
	passwordRegisterRes()
}

type PolicyConsentRes interface {
	policyConsentRes()
}

type PostConclusionRes interface {
	postConclusionRes()
}

type PostImageRes interface {
	postImageRes()
}

type PostOpinionPost2Res interface {
	postOpinionPost2Res()
}

type PostOpinionPostRes interface {
	postOpinionPostRes()
}

type PostTimeLineItemRes interface {
	postTimeLineItemRes()
}

type RegisterUserRes interface {
	registerUserRes()
}

type ReportOpinionRes interface {
	reportOpinionRes()
}

type SessionsHistoryRes interface {
	sessionsHistoryRes()
}

type SolveOpinionReportRes interface {
	solveOpinionReportRes()
}

type SwipeOpinionsRes interface {
	swipeOpinionsRes()
}

type TalkSessionAnalysisRes interface {
	talkSessionAnalysisRes()
}

type TestRes interface {
	testRes()
}

type Vote2Res interface {
	vote2Res()
}

type VoteRes interface {
	voteRes()
}
