// Code generated by ogen, DO NOT EDIT.
package oas

type AuthorizeRes interface {
	authorizeRes()
}

type CreateTalkSessionRes interface {
	createTalkSessionRes()
}

type DevAuthorizeRes interface {
	devAuthorizeRes()
}

type DummiInitRes interface {
	dummiInitRes()
}

type EditTalkSessionRes interface {
	editTalkSessionRes()
}

type EditTimeLineRes interface {
	editTimeLineRes()
}

type EditUserProfileRes interface {
	editUserProfileRes()
}

type GetConclusionRes interface {
	getConclusionRes()
}

type GetOpenedTalkSessionRes interface {
	getOpenedTalkSessionRes()
}

type GetOpinionDetailRes interface {
	getOpinionDetailRes()
}

type GetOpinionsForTalkSessionRes interface {
	getOpinionsForTalkSessionRes()
}

type GetTalkSessionDetailRes interface {
	getTalkSessionDetailRes()
}

type GetTalkSessionListRes interface {
	getTalkSessionListRes()
}

type GetTalkSessionReportRes interface {
	getTalkSessionReportRes()
}

type GetTimeLineRes interface {
	getTimeLineRes()
}

type GetUserInfoRes interface {
	getUserInfoRes()
}

type OAuthCallbackRes interface {
	oAuthCallbackRes()
}

type OAuthTokenInfoRes interface {
	oAuthTokenInfoRes()
}

type OAuthTokenRevokeRes interface {
	oAuthTokenRevokeRes()
}

type OpinionCommentsRes interface {
	opinionCommentsRes()
}

type OpinionsHistoryRes interface {
	opinionsHistoryRes()
}

type PostConclusionRes interface {
	postConclusionRes()
}

type PostOpinionPostRes interface {
	postOpinionPostRes()
}

type PostTimeLineItemRes interface {
	postTimeLineItemRes()
}

type RegisterUserRes interface {
	registerUserRes()
}

type SessionsHistoryRes interface {
	sessionsHistoryRes()
}

type SwipeOpinionsRes interface {
	swipeOpinionsRes()
}

type TalkSessionAnalysisRes interface {
	talkSessionAnalysisRes()
}

type TestRes interface {
	testRes()
}

type VoteRes interface {
	voteRes()
}
