// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package model

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Opinion struct {
	OpinionID       uuid.UUID
	TalkSessionID   uuid.UUID
	UserID          uuid.UUID
	OpinionContent  string
	ParentOpinionID uuid.NullUUID
	VoteID          uuid.NullUUID
	CreatedAt       time.Time
}

type Session struct {
	SessionID      uuid.UUID
	UserID         uuid.UUID
	Provider       string
	SessionStatus  int32
	ExpiresAt      time.Time
	CreatedAt      time.Time
	LastActivityAt time.Time
}

type TalkSession struct {
	TalkSessionID uuid.UUID
	OwnerID       uuid.UUID
	Theme         string
	FinishedAt    sql.NullTime
	CreatedAt     time.Time
}

type User struct {
	UserID      uuid.UUID
	DisplayID   string
	DisplayName string
	Picture     sql.NullString
	CreatedAt   time.Time
}

type UserAuth struct {
	UserID    uuid.NullUUID
	Provider  string
	Subject   string
	CreatedAt time.Time
}

type Vote struct {
	VoteID    uuid.UUID
	OpinionID uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}
