{
  "openapi": "3.0.1",
  "info": {
    "title": "polis",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "talk_session"
    },
    {
      "name": "talk_session/opinion"
    },
    {
      "name": "talk_session/opinion/intention"
    },
    {
      "name": "user"
    },
    {
      "name": "TalkSession"
    },
    {
      "name": "User"
    },
    {
      "name": "Opinion"
    },
    {
      "name": "Intention"
    }
  ],
  "paths": {
    "/api/talksessions/{talkSessionId}": {
      "get": {
        "summary": "トークセッションの詳細",
        "deprecated": false,
        "description": "",
        "operationId": "getTalkSessionDetail",
        "tags": [
          "talk_session",
          "TalkSession"
        ],
        "parameters": [
          {
            "name": "talkSessionId",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/talkSession"
                }
              }
            }
          }
        },
        "security": [],
        "x-ogen-operation-group": "TalkSession"
      }
    },
    "/api/talksessions": {
      "post": {
        "summary": "トークセッション作成",
        "deprecated": false,
        "description": "",
        "operationId": "createTalkSession",
        "tags": [
          "talk_session",
          "TalkSession"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "talkSessionID": {
                      "type": "string"
                    },
                    "talkSessionTheme": {
                      "type": "string"
                    },
                    "talkSessionStatus": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "talkSessionID",
                    "talkSessionTheme",
                    "talkSessionStatus"
                  ]
                }
              }
            }
          }
        },
        "security": [],
        "x-ogen-operation-group": "TalkSession"
      },
      "get": {
        "summary": "トークセッションリスト",
        "deprecated": false,
        "description": "",
        "operationId": "getTalkSessions",
        "tags": [
          "talk_session",
          "TalkSession"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": [],
        "x-ogen-operation-group": "TalkSession"
      }
    },
    "/api/user": {
      "get": {
        "summary": "ユーザー情報の取得",
        "deprecated": false,
        "description": "",
        "operationId": "getUserProfile",
        "tags": [
          "user",
          "User"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "displayID": {
                      "type": "string",
                      "x-apidog-mock": "{{$string.uuid}}"
                    },
                    "displayName": {
                      "type": "string",
                      "x-apidog-mock": "{{$person.firstName}}"
                    }
                  },
                  "required": [
                    "displayID",
                    "displayName"
                  ]
                }
              }
            }
          }
        },
        "security": [],
        "x-ogen-operation-group": "User"
      },
      "post": {
        "summary": "ユーザー作成",
        "deprecated": false,
        "description": "",
        "operationId": "registerUser",
        "tags": [
          "user",
          "User"
        ],
        "parameters": [
          {
            "name": "displayName",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "displayID",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "displayID": {
                      "type": "string",
                      "x-apidog-mock": "{{$string.uuid}}"
                    },
                    "displayName": {
                      "type": "string",
                      "x-apidog-mock": "{{$person.firstName}}"
                    }
                  },
                  "required": [
                    "displayID",
                    "displayName"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "ValidationErroResponse",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          },
          "500": {
            "description": "ServerErrorResponse",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": [
          {
            "SessionId": []
          }
        ],
        "x-ogen-operation-group": "User"
      },
      "put": {
        "summary": "ユーザー情報の変更",
        "deprecated": false,
        "description": "",
        "operationId": "editUserProfile",
        "tags": [
          "user",
          "User"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "displayID": {
                      "type": "string",
                      "x-apidog-mock": "{{$string.uuid}}"
                    },
                    "displayName": {
                      "type": "string",
                      "x-apidog-mock": "{{$person.firstName}}"
                    }
                  },
                  "required": [
                    "displayID",
                    "displayName"
                  ]
                }
              }
            }
          }
        },
        "security": [],
        "x-ogen-operation-group": "User"
      }
    },
    "/api/talksession/{talkSessionID}/opinions": {
      "get": {
        "summary": "セッションの意見一覧",
        "deprecated": false,
        "description": "",
        "operationId": "listOpinions",
        "tags": [
          "talk_session/opinion",
          "Opinion"
        ],
        "parameters": [
          {
            "name": "talkSessionID",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "parentOpinionID",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/opinion"
                  }
                }
              }
            }
          },
          "500": {
            "description": "ServerErrorResponse",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": [],
        "x-ogen-operation-group": "Opinion"
      }
    },
    "/api/talksessions/{talkSessionID}/opinions": {
      "post": {
        "summary": "セッションに対して意見投稿",
        "deprecated": false,
        "description": "",
        "operationId": "postOpinionPost",
        "tags": [
          "talk_session/opinion",
          "Opinion"
        ],
        "parameters": [
          {
            "name": "talkSessionID",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "opinionContent",
            "in": "query",
            "description": "意見の内容",
            "required": true,
            "example": "オブジェクト思考は悪だと思う",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          },
          "500": {
            "description": "ServerErrorResponse",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": [],
        "x-ogen-operation-group": "Opinion"
      }
    },
    "/api/talksessions/{talkSessionID}/opinions/{opinionID}/intentions": {
      "post": {
        "summary": "意思表明API",
        "deprecated": false,
        "description": "",
        "operationId": "indicateIntention",
        "tags": [
          "talk_session/opinion/intention",
          "Intention"
        ],
        "parameters": [
          {
            "name": "talkSessionID",
            "in": "path",
            "description": "セッションのID",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "opinionID",
            "in": "path",
            "description": "意見のID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/opinion"
                  }
                }
              }
            }
          },
          "500": {
            "description": "ServerErrorResponse",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": [],
        "x-ogen-operation-group": "Intention"
      }
    }
  },
  "components": {
    "schemas": {
      "opinion": {
        "type": "object",
        "properties": {
          "opinionID": {
            "type": "string",
            "faker": "1",
            "description": "意見ID"
          },
          "opinionContent": {
            "type": "string",
            "description": "意見のテキスト",
            "minLength": 1,
            "maxLength": 140
          },
          "parentOpinionID": {
            "type": "string",
            "description": "親の意見ID。ルートならば無し"
          }
        },
        "required": [
          "opinionID",
          "opinionContent"
        ]
      },
      "user": {
        "type": "object",
        "properties": {
          "displayID": {
            "type": "string",
            "x-apidog-mock": "{{$string.uuid}}"
          },
          "displayName": {
            "type": "string",
            "x-apidog-mock": "{{$person.firstName}}"
          }
        },
        "required": [
          "displayID",
          "displayName"
        ]
      },
      "error": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "string"
          }
        },
        "required": [
          "code",
          "message",
          "data"
        ]
      },
      "validationErrorItem": {
        "type": "object",
        "properties": {
          "field": {
            "type": "string",
            "faker": "id",
            "description": "バリデーションエラーのフィールド"
          },
          "message": {
            "type": "string",
            "description": "バリデーションエラーメッセージ"
          }
        },
        "required": [
          "field",
          "message"
        ]
      },
      "talkSession": {
        "type": "object",
        "properties": {
          "talkSessionID": {
            "type": "string"
          },
          "talkSessionTheme": {
            "type": "string"
          },
          "talkSessionStatus": {
            "type": "string"
          }
        },
        "required": [
          "talkSessionID",
          "talkSessionTheme",
          "talkSessionStatus"
        ]
      }
    },
    "securitySchemes": {
      "SessionId": {
        "type": "apiKey",
        "in": "cookie",
        "name": "SessionId"
      }
    }
  },
  "servers": []
}
