openapi: 3.0.1
info:
  title: cats-dream
  description: ''
  version: 1.0.0
paths:
  $ref: './apidog.openapi.yaml#/paths'
  /auth/{provider}/login:
    $ref: './paths/authorize.yaml'
  /auth/{provider}/callback:
    $ref: './paths/callback.yaml'
  /auth/revoke:
    $ref: './paths/revoke.yaml'
  /manage:
    $ref: './paths/manage/index.yaml'
  /manage/regenerate:
    $ref: './paths/manage/regenerate.yaml'
components:
  $ref: './apidog.openapi.yaml#/components'
