name: Branch Source Check

on:
  pull_request:
    branches:
      - 'main'

jobs:
  check_develop_source:
    name: Check PR Source
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR source
        run: |
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "mainへのマージはdevelopからのみ許可されています。"
            exit 1
          fi
