name: Deploy to Koyeb
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_KEY }}"

      - name: Trigger Deployment
        run: |
          koyeb service redeploy slim-fanya/kotohiro-server
