name: Prevent Merging from Main to Develop

on:
  pull_request:
    branches:
      - develop

jobs:
  check-merge-direction:
    if: ${{ github.base_ref == 'develop' && github.head_ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fail if merging from main to develop
        run: |
          echo "Merging from 'main' to 'develop' is not allowed."
          exit 1
